// Package
package rouletterouse;

// Libraries
import javax.sound.sampled.*; 
import javax.swing.JOptionPane;
import java.util.Random;

// Class GUI
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_fire = new javax.swing.JButton();
        jButton_charge = new javax.swing.JButton();
        jLabel_image1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Russian Roulette");

        jButton_fire.setText("Fire");
        jButton_fire.setEnabled(false);
        jButton_fire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fireActionPerformed(evt);
            }
        });

        jButton_charge.setText("Charge");
        jButton_charge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_chargeActionPerformed(evt);
            }
        });

        jLabel_image1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documentos\\NetBeansProjects\\RouletteRouse\\src\\resources\\gun.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_fire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_charge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel_image1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_fire, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_charge, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_image1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_fireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fireActionPerformed
        // Generate random bullet & charge
        Random random = new Random();
        int randomBullet = random.nextInt(6) + 1;
        int randomCharge = random.nextInt(6) + 1;
            
            if(randomCharge == randomBullet){
                try{
                    // Create a new AudioInputStream object
                    AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource("/resources/fire.wav"));
                    
                     // Create a new Clip object
                    Clip clip = AudioSystem.getClip();
                    
                    // Open the Clip object
                    clip.open(audioInputStream);
                    
                    // Start the Clip object
                    clip.start();
                    
                    // Game Over Screen
                    JOptionPane.showMessageDialog(null, "GAME OVER", "YOU'RE DEAD", JOptionPane.PLAIN_MESSAGE);
                    jButton_fire.setEnabled(false);
                    jButton_charge.setEnabled(true);
                    
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Couldn't play audio", "Error sound", JOptionPane.ERROR_MESSAGE);
                }
            } else if(randomCharge != randomBullet) {
                try{
                    // Create a new AudioInputStream object
                    AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource("/resources/no_bullets.wav"));
                    
                     // Create a new Clip object
                    Clip clip = AudioSystem.getClip();
                    
                    // Open the Clip object
                    clip.open(audioInputStream);
                    
                    // Start the Clip object
                    clip.start();
                    
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Couldn't play audio", "Error sound", JOptionPane.ERROR_MESSAGE);
                }
            }
    }//GEN-LAST:event_jButton_fireActionPerformed

    private void jButton_chargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_chargeActionPerformed
        try {
            // Create a new AudioInputStream object
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource("/resources/charge.wav"));
            // Create a new Clip object
            Clip clip = AudioSystem.getClip();
            // Open the Clip object
            clip.open(audioInputStream);
            // Start the Clip object
            clip.start();
            
            // Enable button fire when audio finish and disable button charge
            jButton_fire.setEnabled(true);
            jButton_charge.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Gun loaded", "Roulette Russian", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Couldn't play audio", "Error sound", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_chargeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_charge;
    private javax.swing.JButton jButton_fire;
    private javax.swing.JLabel jLabel_image1;
    // End of variables declaration//GEN-END:variables
}
